# Author: Lucas Fernando
# Project: Hands Seals Detection
# Project repository: https://github.com/lucasfernandoprojects/hand-sign-detection
# This config file tells the YOLO model where is located the dataset and what classes it will learn.

path: YOUR_DATASET_ROOT_PATH
train: images/train
val: images/val
test: images/test

# Classes
names:
  0: Saru (monkey)
  1: Tatsu (dragon)
  2: Ne (rat)
  3: Tori (bird)
  4: Mi (snake)
  5: Ushi (ox)
  6: Inu (dog)
  7: Uma (horse)
  8: Tora (tiger)
  9: I (boar)
  10: Hitsuji (ram)
  11: U (hare)
